apps/apps/urls.py
from dashboards.views import IndexView
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path("", IndexView.as_view(template_name="index.html"), name="index"),
    path("", include("users.urls")),
    path("books/", include("books.urls")),
    path("commutes/", include("commutes.urls")),
    path("dashboard/", include("dashboards.urls")),
    path("admin/", admin.site.urls),
]

apps/commutes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.CommuteListView.as_view(), name="commute_list"),
    path("register/", views.register_commutes, name="register_commutes"),
    path("<int:pk>/edit/", views.CommuteUpdateView.as_view(), name="edit_commutes"),
    path("<int:pk>/delete/", views.CommuteDeleteView.as_view(), name="delete_commutes"),
]

apps/commutes/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .utils import CommuteUsageTypes

User = get_user_model()


class Commute(models.Model):
    """交通費"""

    usage_type = models.IntegerField(
        "利用種別", choices=CommuteUsageTypes.choices(), default=CommuteUsageTypes.TO_WORK
    )
    usage_text = models.CharField(
        "種別「その他」の場合に入力", max_length=255, null=True, blank=True
    )
    departure_station = models.CharField("出発駅", max_length=255)
    arrival_station = models.CharField("到着駅", max_length=255)
    price = models.DecimalField("金額", max_digits=10, decimal_places=2)
    date_of_use = models.DateField("利用日")
    has_apply = models.BooleanField("申請済み", default=False)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{CommuteUsageTypes(self.usage_type).name} / {self.date_of_use} / {self.price}"

    def get_commute_usage_type_label(self):
        return CommuteUsageTypes(self.usage_type).name.title()

apps/commutes/forms.py
from django import forms

from .appmodels import complete_stations
from .models import Commute
from .utils import CommuteUsageTypes
from .utils import dates_str_to_dates


class CommuteForm(forms.Form):
    """交通費の登録フォーム

    利用日はカンマ区切りで複数日入力可能

    """

    USAGE_CHOICES = ((1, "出社"), (2, "打ち合わせ"), (3, "その他"))
    ROUTE_CHOICES = ((1, "自宅〜会社"), (2, "その他"))
    usage_type = forms.TypedChoiceField(
        label="利用種別",
        choices=USAGE_CHOICES,
        widget=forms.RadioSelect,
        coerce=int,
        empty_value=None,
    )
    usage_text = forms.CharField(
        label="利用種別「その他」の場合に入力", max_length=255, required=False
    )
    route = forms.TypedChoiceField(
        label="経路",
        choices=ROUTE_CHOICES,
        widget=forms.RadioSelect,
        coerce=int,
        empty_value=None,
    )
    departure_station = forms.CharField(label="出発駅", max_length=255, required=False)
    arrival_station = forms.CharField(label="到着駅", max_length=255, required=False)
    date_of_use = forms.CharField(
        label="利用日",
        widget=forms.TextInput(
            attrs={
                "class": "input datepicker-here",
                "data-language": "en",
                "id": "datepicker",
                "data-multiple-dates": "true",
                "data-multiple-dates-separator": ",",
                "data-date-format": "yyyy/m/d",
                "autocomplete": "off",
                "data-position": "top left",
            }
        ),
    )
    price = forms.DecimalField(label="金額")
    is_round_trip = forms.BooleanField(label="往復？", required=False)
    has_apply = forms.BooleanField(label="申請済み？", required=False)

    def clean_usage_type(self):
        usage_type = self.cleaned_data.get("usage_type")
        return CommuteUsageTypes(usage_type)

    def clean(self):
        route = self.cleaned_data.pop("route")
        _departure_station = self.cleaned_data.get("departure_station")
        _arrival_station = self.cleaned_data.get("arrival_station")
        _date_of_use = self.cleaned_data.get("date_of_use")

        departure_station, arrival_station = complete_stations(
            route, _departure_station, _arrival_station
        )
        self.cleaned_data["departure_station"] = departure_station
        self.cleaned_data["arrival_station"] = arrival_station

        dates_of_use = dates_str_to_dates(_date_of_use)
        self.cleaned_data["date_of_use"] = dates_of_use

    def get_cleaned_results(self):
        fields = (
            "usage_type",
            "usage_text",
            "departure_station",
            "arrival_station",
            "date_of_use",
            "price",
            "is_round_trip",
            "has_apply",
        )
        results = []
        if self.is_valid():
            r = {f: self.cleaned_data[f] for f in fields}
            is_round_trip = r.pop("is_round_trip")
            for date_of_use in r["date_of_use"]:
                d = r.copy()
                d["date_of_use"] = date_of_use
                results.append(d)
                if is_round_trip:
                    c = d.copy()
                    c["departure_station"], c["arrival_station"] = (
                        d["arrival_station"],
                        d["departure_station"],
                    )
                    results.append(c)
            return results
        else:
            return None


class CommuteUpdateForm(forms.ModelForm):
    class Meta:
        model = Commute
        exclude = ("user",)

apps/commutes/views.py
import dacite
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .appmodels import CommuteApp
from .forms import CommuteForm
from .forms import CommuteUpdateForm
from .messengers import CommuteRegisterInputDto
from .models import Commute
from .repositories import CommuteRepository


class CommuteListView(generic.ListView):
    model = Commute
    context_object_name = "commutes"
    template_name = "commutes/list.html"
    ordering = ["-date_of_use", "usage_type"]
    repository = CommuteRepository()

    def get_queryset(self):
        object_list = self.repository.get_user_commutes(
            self.request.user.pk, self.ordering
        )
        return object_list


class CommuteUpdateView(generic.UpdateView):
    model = Commute
    form_class = CommuteUpdateForm
    success_url = reverse_lazy("commute_list")
    template_name = "commutes/edit.html"


class CommuteDeleteView(generic.DeleteView):
    model = Commute
    success_url = reverse_lazy("commute_list")
    template_name = "commutes/delete.html"


def register_commutes(request):
    """交通費を登録するビュー関数"""
    form = CommuteForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            commute_repo = CommuteRepository()
            commute_app = CommuteApp(commute_repo)
            cleaned_results = form.get_cleaned_results()
            commutes = [dict(user_id=request.user.pk, **d) for d in cleaned_results]
            input_dto = dacite.from_dict(
                CommuteRegisterInputDto, dict(commutes=commutes)
            )
            commute_app.create_commute_by_register_form(input_dto)
            return redirect("commute_list")
    context = {"form": form}
    return render(request, "commutes/register.html", context)

apps/templates/commutes/delete.html
{% extends "_base.html" %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="content">
        <h1 class="title is-4">
          <span class="icon is-large">
            <i class="fas fa-subway"></i>
          </span>
          交通費削除
        </h1>
        <form method="post">{% csrf_token %}
          <p>削除しますか？ "{{ object }}"?</p>
          <button type="submit" class="button is-danger">削除</button>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

apps/templates/commutes/edit.html
{% extends "_base.html" %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css" integrity="sha256-q0wZgzQ6Ru67x+pIe9IAztrnlHNHyZui3BMwqUYDnpI=" crossorigin="anonymous" />
{% endblock css %}

{% block footer_js %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js" integrity="sha256-0prQxFtdWQNa3vW5JDMbvbBp6ehKzf9UIWqFGZIWPPE=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js" integrity="sha256-RbE9ux8UbaKexk/+aT9XkZ8tcUWg3yw/3XE/S8iW7eI=" crossorigin="anonymous"></script>
<script>
$(function() {

  $("[name=usage_type]").change(function() {
    if($("#id_usage_type_2").prop("checked")) {
      $("#id_usage_text").prop("disabled", false)
    }else{
      $("#id_usage_text").prop("disabled", true)
    }
  });

})

</script>
{% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="content">
        <h1 class="title is-4">
          <span class="icon is-large">
            <i class="fas fa-subway"></i>
          </span>
          交通費を編集
        </h1>
        <form action="{% url 'edit_commutes' commute.pk %}" method="post">
          {% include "_components/commute_edit_form.html" %}
          {% csrf_token %}
        </form>
      </div>
    </div>
  </section>
{% endblock %}

apps/templates/commutes/list.html
{% extends "_base.html" %}
{% block content %}
  <section class="section">
    <div class="container">
      <div class="content">
        <h1 class="title is-4">
          <span class="icon is-large">
            <i class="fas fa-subway"></i>
          </span>
          交通費一覧
        </h1>
        <div class="table-container">
          <p>
          <div class="buttons has-addons is-right">
            <a class="button is-dark is-right" href="{% url 'register_commutes' %}">交通費登録</a>
          </div>
          </p>
          {% include "_components/commutes_table.html" with commutes=commutes %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

apps/templates/commutes/register.html
{% extends "_base.html" %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css" integrity="sha256-q0wZgzQ6Ru67x+pIe9IAztrnlHNHyZui3BMwqUYDnpI=" crossorigin="anonymous" />
{% endblock css %}

{% block footer_js %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js" integrity="sha256-0prQxFtdWQNa3vW5JDMbvbBp6ehKzf9UIWqFGZIWPPE=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.min.js" integrity="sha256-RbE9ux8UbaKexk/+aT9XkZ8tcUWg3yw/3XE/S8iW7eI=" crossorigin="anonymous"></script>
<script>
$(function() {

  $("[name=usage_type]").change(function() {
    if($("#id_usage_type_2").prop("checked")) {
      $("#id_usage_text").prop("disabled", false)
    }else{
      $("#id_usage_text").prop("disabled", true)
    }
  });

  $("[name=route]").change(function() {
    if($("#id_route_1").prop("checked")) {
      $("#id_departure_station").prop("disabled", false);
      $("#id_arrival_station").prop("disabled", false);

    }else{
      $("#id_departure_station").prop("disabled", true);
      $("#id_arrival_station").prop("disabled", true);
    }
  });

})

</script>
{% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="content">
        <h1 class="title">交通費を登録</h1>
        <div class="box">
          {% include "_components/commute_register_form.html" with form=form %}
        </div>
      </div>
    </div>
  </section>
{% endblock content %}